// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketApp.Data;

#nullable disable

namespace TicketApp.Migrations
{
    [DbContext(typeof(TicketAppContext))]
    [Migration("20221111032752_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TicketApp.Models.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tech");
                });

            modelBuilder.Entity("TicketApp.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("TechId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechId1")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("TechId1");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            TicketId = 2,
                            CreatedDate = new DateTime(2022, 11, 10, 22, 27, 51, 747, DateTimeKind.Local).AddTicks(259),
                            Description = "Laptop",
                            EndDate = new DateTime(2022, 11, 10, 22, 27, 51, 747, DateTimeKind.Local).AddTicks(304),
                            Location = "UP303",
                            Notes = "None",
                            Priority = 0
                        });
                });

            modelBuilder.Entity("TicketApp.Models.Ticket", b =>
                {
                    b.HasOne("TicketApp.Models.Tech", "Tech")
                        .WithMany("Tickets")
                        .HasForeignKey("TechId1");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("TicketApp.Models.Tech", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
